### ISSUE TITLE
Using lib3to6 with ax & botorch

### ISSUE THREAD

**Issue by Mita2049** [mbarkhau/lib3to6#2]
Hi,

I recently used lib3to6 on ax and botorch (two scientific/experimentation libraries by Facebook). My target platform was python 3.6. All in all, lib3to6 worked really great, but here's some things where it was having problems with (mostly more complicated forward references and cyclic imports). I integrated it in setup.py directly, btw.

Hope this helps with future development, btw.

WHAT I HAD TO MODIFY TO GET IT TO WORK PROPERLY
**lib3to6/checkers.py**
replace
`if name_in_scope in common.BUILTIN_NAMES:`
with
`if name_in_scope in common.BUILTIN_NAMES and name_in_scope not in ["oct", "buffer", "input", "file", "xrange", "reduce", "type", "eval", "repr", "id", "filter", "callable", "object", "min", "max", "format", "display", "sum"]:` (didn't know how to disable builtins via setup.py)

**lib3to6/fixers.py**
replace
`elif isinstance(val, ast.Tuple):`
with
`elif isinstance(val, ast.Tuple) or isinstance(val, ast.List):`

WHAT IT COULDN'T REALLY DEAL WITH OR HAS MISSED
**botorch/utils/sampling.py**
def draw_sobol_samples(
   bounds: Tensor,
   n: int,
   q: int,
   batch_shape=None, # Optional[Iterable[int], torch.Size] = None, (this type hint)
   seed: Optional[int] = None,
) -> Tensor:

**botorch/acquisition/knowledge_gradient.py**
def _get_value_function(
   model: Model,
   objective: Optional[Union[MCAcquisitionObjective, ScalarizedObjective]] = None,
   sampler: Optional[MCSampler] = None,
   project: Optional[Callable[[Tensor], Tensor]] = None,
   valfunc_cls: Optional[Type[AcquisitionFunction]] = None,
   valfunc_argfac=None, # Optional[Callable[[Model, Dict[str, Any]]]] = None, (this type hint)
) -> AcquisitionFunction:

**ax/core/observation.py**
remove from ax.core.batch_trial import BatchTrial
replace if not include_abandoned and isinstance(trial, BatchTrial): with if not include_abandoned and trial.__class__.__name__ == "BatchTrial"

**ax/core/metric.py**
core.base_trial.BaseTrial
core.experiment.Experiment

**ax/modelbridge/modelbridge_utils.py**
modelbridge_module.array.ArrayModelBridge hint
modelbridge_module.base.ModelBridge hint

**ax/storage/sqa_store/db.py**
nullcontext import

**ax/core/data.py** (this will break lib3to6)
return super().column_data_types(
    {**(extra_column_types or {}), **(column_data_types or {})}
)

**ax/modelbridge/torch.py** (this will break lib3to6)
augmented_model_gen_options = {
    **self._default_model_gen_options,
    **(model_gen_options or {}),
}

**ax/models/torch/tests/test_list_surrogate.py** (this will break lib3to6)
def check_ranks(self, c: ListSurrogate) (problem was return type)

**ax/models/torch/botorch_modular/surrogate.py** (this will break lib3to6)
input_constructor_kwargs = {**self.model_options, **(kwargs or {})}

**ax/models/torch/botorch_modular/acquisition.py** (this will break lib3to6)
optimizer_options_with_defaults = {
    **get_default_optimizer_options(acqf_class=self.botorch_acqf_class),
    **(optimizer_options or {}),
}

**Comment by mbarkhau** [comment]
Hi @Mita2049,

thank you for this feedback. Just for clarification, did you eventually get it to work?

**Comment by mbarkhau** [comment]
Is it possible you have configured lib3to6 for an older target version than you need to. Some of the errors relate to unpacking generalizations and I don't think the fixer for that should be running if you have `python_requires=">=3.6"`. 

Can you test with the newest beta: https://pypi.org/project/lib3to6/202108.1048b3/
And the new integration method: https://github.com/mbarkhau/lib3to6#integration-with-setuppy

If the errors persist, could you add the error messages you mean by "this will break lib3to6" and point me to your forks of these libraries, so I can see the setup.py you are using?

**Comment by mbarkhau** [comment]
@Mita2049 Feel free to reopen if you have time to help further.
